title: Rita Sule # your name (or website title) here
logo: "/images/rita-sule-photo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Science Enthusiast 
  <br><br>
  <br><br>
  <a href="https://uk.linkedin.com/in/rita-sule-372344134">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal-elcyon
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
